<?php
      // SVG export example
      
      //Includes
      include "../../../../sources/TChart.php";      
      
      // Assign Header text
      $chart1 = new TChart(600,450);
      $chart1->getHeader()->setText("SVG Export");
      $chart1->getPanel()->getGradient()->setVisible(false);      
      $chart1->getPanel()->setColor(Color::WHITE());
            
      // Add Series to the Chart
      $bar1 = new Bar($chart1->getChart());
      $bar1->fillSampleValues(15);
      $bar1->setColorEach(true);      
	  $chart1->getChart()->getAxes()->getBottom()->getLabels()->setAngle(45);
	  
      $bar1->getMarks()->setVisible(false);
      $chart1->getWalls()->getBack()->setTransparent(true);
   
      print '<font face="Verdana" size="2">SVG Export autogenerated!<p>';     
      echo  $chart1->getChart()->getExport()->getImage()->getSVG()->Render()->toString();        
?>